### ISSUE TITLE
resolve depcheck warnings

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-cloudmanager#109]
```
$ npx depcheck
Unused dependencies
* @oclif/config
* @oclif/errors
* @oclif/plugin-help
* zlib
Missing dependencies
* execa: ./e2e/e2e.js
* lodash: ./src/client.js
* @adobe/aio-cli-plugin-config: ./test/fixtures/scripts/global-setup.js
```

devDep warnings removed because I think they are false positives.

**Comment by justinedelson** [comment]
`@oclif/plugin-help` is a false positive as well. This is a peer dependency of `@oclif/command` and if not listed, causes a warning on install.

Rest of these are fixed by #113
