### ISSUE TITLE
Sync Github Issues with JIRA

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-cloudmanager#121]
If you want this functionality, please add `aiojbot` to your repo under `Settings -> Manage Access` under a `Triage` role. Thanks.

The sync functionality runs every 15 minutes, and will watch for label events in issues. (bug, enhancement, question, feature)

**Comment by justinedelson** [comment]
I don't think this is necessary. But it seems like it is enabled even though aiojbot wasn't added.
