### ISSUE TITLE
Description of tail-log and download-logs is incorrect

### ISSUE THREAD

**Issue by mirkogolze** [adobe/aio-cli-plugin-cloudmanager#142]
In the documentation for https://github.com/adobe/aio-cli-plugin-cloudmanager/blob/main/README.md#aio-cloudmanagerdownload-logs-environmentid-service-name-days and https://github.com/adobe/aio-cli-plugin-cloudmanager/blob/main/README.md#aio-cloudmanagertail-log-environmentid-service-name is written "lists available logs for an environment in a Cloud Manager program"

For both commands, this is not really the case. Could you please improve the description?
For people don't have access to a sandbox it would be easier to unterstand.

**Comment by justinedelson** [comment]
@mirkogolze can you clarify what you mean? Is the issue that this needs to be qualified to apply only to Cloud Service programs?

**Comment by mirkogolze** [comment]
This only faces to the documentation in the README.md for this git repository.
For the documentation of "aio cloudmanager:download-logs ENVIRONMENTID SERVICE NAME [DAYS]" I would think the following description is better than "lists available logs for an environment in a Cloud Manager program":

"download the log files for an environment in a Cloud Manager program" 
Some explainations can be helpful. E.g. how the number of days will work.

**Comment by justinedelson** [comment]
Ah. I get it now. Sorry, misunderstood. Indeed this is a copy/paste issue. Fixed in #143
