### ISSUE TITLE
environment variable aemCloudAdministrators not exposed via list-environment-variables

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#144]
Although in the OSGi configuration for PID `org.apache.jackrabbit.oak.security.authorization.AuthorizationConfigurationImpl` I see the value `[administrators, $[env:aemCloudAdministrators;default=administrators]]` being set for property `administrativePrincipals`, the environment variable called `aemCloudAdministrators` is not listed via `aio cloudmanager:list-environment-variables` for that particular environment. Still is must have a certain value as all users being member of a cryptic group `AEM Administrators-3e6e8bd0a05f39bc82d788bb27ac83b4` are being administrators!

Please make sure that all environment variables are exposed from `aio cloudmanager:list-environment-variables` (even the ones which may be set as start argument)

**Comment by justinedelson** [comment]
I don't know where this variable is coming from but if it is not visible in the output of the variables API it must be coming from some other place than these variables.
