### ISSUE TITLE
Add support to set a default environment ID

### ISSUE THREAD

**Issue by josephrignanese** [adobe/aio-cli-plugin-cloudmanager#149]
### Expected Behaviour

There is currently the capability to set a default program ID. It would be an improvement to also allow the users to specify a default environment ID in a similar way.

This would allow users to avoid passing the environment ID repeatedly when executing multiple commands against a single environment, e.g. list-environment-variables then set-environment-variables.

**Comment by josephrignanese** [comment]
To support the existing argument pattern of the `download-logs` and `tail-log` commands is not straight forward. It seems to add an optional first arg would require some logic introduced into the command to try to pre-determine which form of arguments a user is trying to specify. e.g. `tail-log` can check the number of args, and `download-logs` can do the same and also check the format of the first or last parameter for the case of 3 args.

The other commands could be modified to have an optional argument for environment and fallback to the configured default when set.

If we do make some breaking changes we might also want to consider alignment with the flags approach used for program id but that would of course mean potentially causing breaking changes to all the environment related commands or attempt to support the usage of the config value, a flag or the argument in those cases.

My questions are:
1. Do we want to avoid breaking changes at the cost of adding complexity to the commands?
2. Do we want to allow the environment id to be specified in a flag instead of, or in addition to, as an argument?

@justinedelson - thoughts?

**Comment by josephrignanese** [comment]
Example of what backwards compatibility could look like: 
https://github.com/josephrignanese/aio-cli-plugin-cloudmanager/blob/591a4f05c8ee68d3c197d7ad069d3398b410c77e/src/commands/cloudmanager/tail-log.js

**Comment by justinedelson** [comment]
@josephrignanese I've been thinking about this on and off and finally had an idea. Maybe (big maybe) it would be possible to accomplish this by using [hooks](https://oclif.io/docs/hooks). The way this would work is that each command that wanted to accept the environmentId via configuration could set a some property on the command object:

```
ListEnvironmentVariablesCommand.hasEnvironmentId = true
```

Then there's a prerun hook that does something like this:

```
module.exports = async function (options) {
  if (options.Command.hasEnvironmentId) {
    const environmentId = // read the environment Id from configuration
    if (environmentId) {
       options.config.environmentId = '123' // to "pass" it to the command
    }    
  }
}
```

And then in the command class...

```
const { args, flags } = this.parse(ListEnvironmentVariablesCommand)
```

becomes

```
    let customArgv = this.argv
    if (this.config.environmentId && this.argv.length !== ListEnvironmentVariablesCommand.args.length) {
      customArgv = [this.config.environmentId, ...customArgv]
    }

    const { args, flags } = this.parse(ListEnvironmentVariablesCommand, customArgv)
```
i.e. if the `config.environmentId` is set and the arguments passed on the CLI doesn't match the length of the expected args, manipulate the arguments array to include it as the first element.
(this could probably be a helper function)

Do you have the bandwidth to try to prove this out?

**Comment by josephrignanese** [comment]
Hey @justinedelson - seems worth a shot

So, I take it that our current position is that we:

1. plan to avoid breaking changes at the cost of adding complexity
2. don't see much value in switching to a flag instead of an argument

I don't have a lot of bandwidth in the next few weeks, but will pick it up when I can if no one has taken it forward 👍

**Comment by justinedelson** [comment]
Yes, I think breaking backwards compatibility should be avoided.

**Comment by justinedelson** [comment]
I did a bit of spiking around this and it turns out to be more complex than I thought. The code above can work, but only if you assume there are no flags specified on the command line, but that's obviously not always the case, e.g. with setting environment variables.

**Comment by justinedelson** [comment]
I figured out a way to do this with try/catch. Seems pretty effective in my local testing.
