### ISSUE TITLE
Accept variables given in a JSON file with all set-...-variables commands

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#150]
Currently all variables have to be set with individual CLI options. To ease setting multiple variables which are being maintained in some external tool in an automated fashion, it would be beneficial to directly allow a JSON file as input to both https://github.com/adobe/aio-cli-plugin-cloudmanager#aio-cloudmanagerset-environment-variables-environmentid and https://github.com/adobe/aio-cli-plugin-cloudmanager#aio-cloudmanagerset-pipeline-variables-pipelineid.

The JSON format could look like this
```
[
  { 
    'name': 'mykey',
    'value': 'myvalue',
    'isSecret': true
 }
 ...
]
```
`value` could be optional so that all variables not having the attribute `value` are automatically deleted.

**Comment by kwin** [comment]
In addition supporting variables in `.properties` format as defined by https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader- would be nice. That would require two separate files: one for secret variables the other one for non-secret variables.

**Comment by justinedelson** [comment]
This is an interesting idea, but thinking of this from Single Responsibility Principal standpoint, wouldn't it be better to implement that using something like jsawk to transform the input?

**Comment by justinedelson** [comment]
@kwin I put together a pull request to enable a JSON array to be passed through stdin if you specify `--stdin` on either of the set-*-variables commands.

There's probably still some test cases I haven't considered, but I wanted to get your take on this.

**Comment by twolfart** [comment]
My 2c: with an option to define input from a file, it would be easier to use the feature in a context without a shell (or varying shells). In my usecase, that could be an npx call from inside Maven.
(using https://github.com/eirslett/frontend-maven-plugin#npx)

**Comment by justinedelson** [comment]
@twolfart This probably warrants a separate issue, but how do you get the plugin to work with `npx`? I have not tried this myself, but it seems like you'd need to run multiple commands.

For a Maven use case, I wonder if it would be more efficient to use groovy (or some other JVM scripting language) and https://github.com/adobe/aio-lib-java-cloudmanager rather than shelling out.

**Comment by twolfart** [comment]
@justinedelson Yes, these are multiple calls. I'm using it in Maven, so there's more boilerplate around it. The main part is:
``` xml
<plugin>
  <groupId>com.github.eirslett</groupId>
  <artifactId>frontend-maven-plugin</artifactId>
  <executions>
    <execution>
      <id>install node and npm</id>
      <goals>
        <goal>install-node-and-npm</goal>
      </goals>
      <phase>generate-resources</phase>
      <configuration>
        <nodeVersion>${nodeVersion}</nodeVersion>
        <npmVersion>${npmVersion}</npmVersion>
      </configuration>
    </execution>
    <execution>
      <id>npm install</id>
      <goals>
        <goal>npm</goal>
      </goals>
      <phase>generate-resources</phase>
      <configuration>
        <arguments>install @adobe/aio-cli</arguments>
      </configuration>
    </execution>
    <execution>
      <id>aio install plugins</id>
      <goals>
        <goal>npx</goal>
      </goals>
      <phase>generate-resources</phase>
      <configuration>
        <arguments>aio plugins:install @adobe/aio-cli-plugin-cloudmanager</arguments>
      </configuration>
    </execution>          
  </executions>
</plugin>
```

After that, the plugin is available. You can also add configuration etc.

This is also a good example for my usecase: stdin is not usable here.

And yes, I agree, there may be more efficient ways to integrate in Maven. But as for now, this connects larger parts of my toolchain very nice, and also follows what is done "by hand", which makes it easy to understand.
