### ISSUE TITLE
tail-log not working on Windows

### ISSUE THREAD

**Issue by shunnaradobe** [adobe/aio-cli-plugin-cloudmanager#174]
### Expected Behaviour
log would be tailed when requested with the tail-log command on windows 10
### Actual Behaviour
error thrown:
`
Warning: cloudmanager:environment:tail-log is not a aio command.

Did you mean cloudmanager:set-environment-variables? [y/n]:

» Error: Run aio help cloudmanager for a list of available commands.
`
### Reproduce Scenario (including but not limited to)
`aio cloudmanager:environment:tail-log 36686 author aemerror
`
#### Steps to Reproduce

1. setup an aio cli on windows
2. test other commands are working fine (e.g. download-logs)
3. test tail-log

#### Windows 10
aio -v
@adobe/aio-cli/5.0.1 win32-x64 node-v14.15.1

**Comment by justinedelson** [comment]
@shunnaradobe what is the output of

> aio plugins

?

**Comment by shunnaradobe** [comment]
Thanks @justinedelson. Output is:
@adobe/aio-cli-plugin-cloudmanager 0.18.2
which seems to be the latest

**Comment by justinedelson** [comment]
FWIW, I have not been able to reproduce this. 

```
C:\Users\Administrator>aio -v
@adobe/aio-cli/5.0.1 win32-x64 node-v14.15.4

C:\Users\Administrator>aio plugins
@adobe/aio-cli-plugin-cloudmanager 0.18.2

C:\Users\Administrator>aio cloudmanager:tail-log
 ›   Error: Missing 3 required args:
 ›   environmentId  the environment id
 ›   service        the service
 ›   name           the log name
 ›   See more help with --help
```

**Comment by justinedelson** [comment]
Short of uninstalling and reinstalling the plugin, it might also be helpful to post a copy of the oclif.manifest.json file here.

It looks like that file can be found in `%LOCALAPPDATA%\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-cloudmanager`

**Comment by justinedelson** [comment]
Also (and again, I couldn't reproduce this with a similar Node version), according to https://github.com/adobe/aio-cli/issues/224#issuecomment-716461901, aio-cli does not support Node v14, only 10 and 12.

**Comment by justinedelson** [comment]
@shunnaradobe any update on this?

**Comment by justinedelson** [comment]
Have not received any feedback, so I assume this is no longer an issue.
