### ISSUE TITLE
Document required product profiles for Adobe IO integrations per command

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aio-cli-plugin-cloudmanager#175]
It would be nice to document what Product Profiles the Adobe IO Cloud Manager API must be a member of to execute each command. 

For example, when my CM API is a member of just the CM - Developer Product Profile, I can tail logs, however, I cannot set environment variables. (This seems to require membership in the Deployment Manager PP).

I dont see this documented

* https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/deploying/configuring-osgi.html?lang=en#deleting-values-via-cli
* Or in the ExL Cloud Manager User Guide

**Comment by kwin** [comment]
This is IMHO documented at https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/permissions.md. A link to that page from the Readme should be sufficient.

**Comment by justinedelson** [comment]
@davidjgonzalez were you going to create a PR for this?

**Comment by justinedelson** [comment]
In addition to updating the README, all of the commands can now be passed `--permissions` as a flag (without any other flags/args) and will output something about the permissions required.
