### ISSUE TITLE
Improve documentation of CLI option values

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#199]
The options of the CLI commands are described like this

`-s, --secret=secret          secret values in KEY VALUE format`
(https://github.com/adobe/aio-cli-plugin-cloudmanager#aio-cloudmanagerenvironmentset-variables-environmentid)

To me this is highly confusing because I don't understand the part `-secret=secret`. In fact you can either use option `-s` or `secret` but both option need to be followed by space, KEY, space and VALUE. There is no `=` to be used with those options.

**Comment by justinedelson** [comment]
To accomodate different user patterns, oclif flags work with either space or `=`.

There's no _need_ to use a space, but `=` is the default recommendation.

Updated the docs with a link to the oclif documentation that explains this.

**Comment by kwin** [comment]
Still something like
```
-s=<secret>, --secret=<secret>  <secret > is KEY VALUE (separated by SPACE)
```
would be way easier to digest IMHO

**Comment by justinedelson** [comment]
This would probably be best to raise in https://github.com/oclif/dev-cli

I'm sure oclif has a reason for using this format for the generated documentation and the risk of *not* generating the documentation is too high IMO.
