### ISSUE TITLE
Clarify requirements with regards to Node version

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#210]
According to https://github.com/adobe/aio-cli-plugin-cloudmanager#requirements every node version newer than 10 is supported. Currently the AIO CLI itself only supports Node 10 or 12 (https://github.com/adobe/aio-cli/issues/247).

**Comment by justinedelson** [comment]
This makes me wonder if there's any value in documenting any Node version here. Seems like just saying that AIO CLI is required should be sufficient -- the transitive restriction is better described by AIO CLI.

WDYT?

**Comment by kwin** [comment]
If the plugin itself doesn't inflict any additional restrictions this sounds good to me.

**Comment by justinedelson** [comment]
It turns out to be a bit more complicated -- aio-cli says it is compatible with any 10.x release, but this plugin requires 10.22.0. So I added some explicit language to the README.
