### ISSUE TITLE
Local .aio file automatically generated in each folder where aio:cloudmanager is executed

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#212]
After the change of https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/129 every execution of `aio cloudmanager:...` creates an `.aio` file in the current directory containing 

```
{
  ims: {
    config: {
      current: "aio-cli-plugin-cloudmanager"
    }
  }
}
```

**Comment by justinedelson** [comment]
Is this a problem?

**Comment by kwin** [comment]
Yes. Needs to be added to .gitignore, pollutes created content-packages, and in general creates unnecessary files on the hard disk.

**Comment by kwin** [comment]
@justinedelson Thanks a lot for that quick fix.
