### ISSUE TITLE
Remove "technical_account_email" from authentication configuration

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#216]
The field `technical_account_email` is never used to generate the access token.
The whole protocol at https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/JWT/JWT.md only relies on `technical_account_id` but not on email. Therefore it does not bring any benefit to include it in the configuration.

**Comment by kwin** [comment]
I also opened https://github.com/adobe/aio-lib-ims/issues/63 for the changes in the upstream library.

**Comment by justinedelson** [comment]
Yeah, I noticed this and during the migration it's set to `unused`. But as you note, https://github.com/adobe/aio-lib-ims#jwt-configuration says it is required.

I guess something could be added to the README that says "`technical_account_email` is technically required by the underlying authentication library but unused by this plugin. Other uses of this context may require it."

**Comment by justinedelson** [comment]
I updated the readme to reflect that this isn't required anymore. Not sure why the bot didn't close this issue.

**Comment by justinedelson** [comment]
Not in my testing.
