### ISSUE TITLE
Allow to install cli-plugin-cloudmanager for all users

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#219]
With ```$ aio plugins:install @adobe/aio-cli-plugin-cloudmanager``` the plugin is only installed for the current user (in Unix/MacOS in folder `<USERHOME>/.local/share/@adobe/aio-cli`. There should be an option to install it globally (i.e. for all users), which would be especially useful if used inside Docker Containers (e.g. Jenkins with JENKINS_HOME usually located on a dedicated persisted volume).
I haven't found an option in oclif-plugin-plugins https://github.com/oclif/plugin-plugins#mycli-pluginsinstall-plugin. But maybe there is some other way to achieve that...

**Comment by justinedelson** [comment]
I don't know if this would work with the configuration pieces, but in theory you can run this plugin independently from aio. I suspect that all that is really missing here is adding the `bin` directive to the `package.json` file.

But then there's a different problem -- `npm install -g` is not really "global" to my knowledge. It's global *for that user*. Does the Jenkins setup you are describing solve that differently?

**Comment by kwin** [comment]
`npm install -g` works fine for me. I use it in my Docker container to install as root and then use npm from the Jenkins user without any issues.
