### ISSUE TITLE
aio cloudmanager:execution:get-step-details should expose action in format accepted by cloudmanager:execution:get-step-log

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#226]
The (JSON) output of the command `aio cloudmanager:execution:get-step-details` exposes something like 
```
...
 {
    "action": "Build Image",
    "status": "Finished",
    "startedAt": "February 19, 2021 7:19 PM",
    "finishedAt": "February 19, 2021 7:42 PM",
    "duration": "23 minutes"
  },
...
```

The action field is not usable as argument for subsequent command `aio cloudmanager:execution:get-step-log` as that expect values like `(build|codeQuality|devDeploy|stageDeploy|prodDeploy|buildImage)`

Instead of building a manual mapping table the former command should expose the actionId (next to the action label) which can be used in subsequent commands as argument.

**Comment by justinedelson** [comment]
This is intentional -- the JSON/YAML outputs are intended to be alternate renderings of the table.

**Comment by kwin** [comment]
Just to clarify: I am not proposing to only add it to JSON, also the textual table should have the column `actionId`. If only the action label is exposed that does not help if you want to call subsequent commands....
