### ISSUE TITLE
Flag imsContextName not correctly considered

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#237]
I installed the aio-cli-plugin-cloudmanager module standalone. When I call

`node_modules/.bin/adobe-cloudmanager-cli cloudmanager:current-execution:cancel 1662149 --programId=29008 --imsContextName=program-29008` I get the error

```
 ›   Error: There is no IMS context configuration defined for 
 ›   ims.contexts.aio-cli-plugin-cloudmanager.
```

As I have  explicitly overwritten the context name, I would assume that the configuration is looked up in `ims.contexts.program-29008` instead of the default `ims.contexts.aio-cli-plugin-cloudmanager`

**Comment by justinedelson** [comment]
Do you have both contexts configured?

**Comment by kwin** [comment]
Only one, my config file looks like this
```
{
  "ims": {
    "contexts": {
      "program-29008": {
        "client_id": "xxx",
        "client_secret": "xxx",
        "technical_account_id": "xxx",
        "technical_account_email": "unused",
        "ims_org_id": "xxx",
        "meta_scopes": [
          "ent_cloudmgr_sdk"
        ],
        "private_key": "xxx"
      }
    }
  }
}
```

**Comment by justinedelson** [comment]
The validation added in the last release assumes you are using imsContextName to specify an “alternate” context name, i.e. you’re configuring 1+ contexts, one of which is the default.

**Comment by kwin** [comment]
I plan to configure additional contexts in the future. What is supposed to be looked up from the default? Is the default always `ims.contexts.aio-cli-plugin-cloudmanager`?

**Comment by justinedelson** [comment]
> What is supposed to be looked up from the default?
As I said, the assumption is that the default is always present and valid.

> Is the default always ims.contexts.aio-cli-plugin-cloudmanager?
Yes
