### ISSUE TITLE
Empty currentStep and currentStepStatus properties at the end of pipeline processing

### ISSUE THREAD

**Issue by jwadolowski** [adobe/aio-cli-plugin-cloudmanager#275]
### Expected Behaviour

`aio cloudmanager:current-execution:get <PIPELINE_ID> -j` should return the last step name and its status in instead of empty values when pipeline is about to be completed.

### Actual Behaviour

At the very end of pipeline processing I get the following output:

```
$ aio cloudmanager:current-execution:get <PIPELINE_ID> -j
[
  {
    "pipelineId": "<PIPELINE_ID>",
    "id": "<ID>",
    "createdAt": "April 12, 2021 6:09 PM",
    "trigger": "MANUAL",
    "currentStep": "",
    "currentStepStatus": ""
  }
]
```

It lasts for at least a few seconds.

### Reproduce Scenario (including but not limited to)

Monitoring of CM pipeline progress from CI platform.

#### Steps to Reproduce

1. Start any CM pipeline
2. Run `aio cloudmanager:current-execution:get <PIPELINE_ID> -j` in a loop to monitor pipeline progress
3. Inspect a few last outputs of aforementioned command

#### Platform and Version

```
$ aio -v
@adobe/aio-cli/6.0.0 darwin-x64 node-v12.22.0

$ aio plugins
@adobe/aio-cli-plugin-cloudmanager 1.4.0
```

#### Sample Code that illustrates the problem

```
$ while true; do aio cloudmanager:current-execution:get <PIPELINE_ID> -j; done
 ›   Error: [CloudManagerSDK:ERROR_GET_EXECUTION] Cannot get execution: https://cloudmanager.adobe.io/api/program/<PROGRAM_ID>/pipeline/<PIPELINE_ID>/execution (404 Not Found) - Pipeline Execution not found(s): No execution in progress:
 ›   programId=<PROGRAM_ID>, pipelineId=<PIPELINE_ID>
[
  {
    "pipelineId": "<PIPELINE_ID>",
    "id": "<ID>",
    "createdAt": "April 12, 2021 6:09 PM",
    "trigger": "MANUAL",
    "currentStep": "Validate",
    "currentStepStatus": "RUNNING"
  }
]

...

[
  {
    "pipelineId": "<PIPELINE_ID>",
    "id": "<ID>",
    "createdAt": "April 12, 2021 6:09 PM",
    "trigger": "MANUAL",
    "currentStep": "Dev Deploy",
    "currentStepStatus": "RUNNING"
  }
]
[
  {
    "pipelineId": "<PIPELINE_ID>",
    "id": "<ID>",
    "createdAt": "April 12, 2021 6:09 PM",
    "trigger": "MANUAL",
    "currentStep": "Dev Deploy",
    "currentStepStatus": "RUNNING"
  }
]
[
  {
    "pipelineId": "<PIPELINE_ID>",
    "id": "<ID>",
    "createdAt": "April 12, 2021 6:09 PM",
    "trigger": "MANUAL",
    "currentStep": "",
    "currentStepStatus": ""
  }
]
[
  {
    "pipelineId": "<PIPELINE_ID>",
    "id": "<ID>",
    "createdAt": "April 12, 2021 6:09 PM",
    "trigger": "MANUAL",
    "currentStep": "",
    "currentStepStatus": ""
  }
]
[
  {
    "pipelineId": "<PIPELINE_ID>",
    "id": "<ID>",
    "createdAt": "April 12, 2021 6:09 PM",
    "trigger": "MANUAL",
    "currentStep": "",
    "currentStepStatus": ""
  }
]
 ›   Error: [CloudManagerSDK:ERROR_GET_EXECUTION] Cannot get execution: https://cloudmanager.adobe.io/api/program/<PROGRAM_ID>/pipeline/<PIPELINE_ID>/execution (404 Not Found) - Pipeline Execution not found(s): No execution in progress:
 ›   programId=<PROGRAM_ID>, pipelineId=<PIPELINE_ID>

```

#### Logs taken while reproducing problem

See above

### Noteworthy facts

To make sure that's not API's fault I decided to call CM API directly in a loop. This is how it looks like at the very end of processing: https://gist.github.com/jwadolowski/dea49b0673a1cb8d9f67ddf887daf8eb

As you can see all the steps have `FINISHED` status, but the top level `status` still says `RUNNING`.

The plugin uses [this](https://github.com/adobe/aio-cli-plugin-cloudmanager/blob/main/src/base-execution-command.js#L63-L79) section to display the result. Both [getLastStepAction](https://github.com/adobe/aio-cli-plugin-cloudmanager/blob/main/src/base-execution-command.js#L19-L22) and [getLastStepStatus](https://github.com/adobe/aio-cli-plugin-cloudmanager/blob/main/src/base-execution-command.js#L24-L27) use [getCurrentStep](https://github.com/adobe/aio-lib-cloudmanager/blob/main/src/helpers.js#L20-L22), which looks for 1st non-FINISHED step. At the end of the pipeline there's no such step, hence fallback to `undefined` and empty string eventually.

This ticket was originally submitted via Adobe support portal: E-000353141

**Comment by justinedelson** [comment]
@jwadolowski can you explain what you are trying to accomplish by calling `aio cloudmanager:current-execution:get <PIPELINE_ID> -j` in a loop like this?

**Comment by jwadolowski** [comment]
For some clients (e.g. from highly regulated industries) public webhooks are quite often a no-go, which means API polling is the only way to determine CM pipeline status. This way we can orchestrate platform deployments and plug various things into the process (e.g. when CM pipeline is done, or reached certain stage, additional tests are executed).

**Comment by justinedelson** [comment]
I _think_ I understand. In this context, you should probably be using the [I/O Events Journaling API](https://www.adobe.io/apis/experienceplatform/events/docs.html#!adobedocs/adobeio-events/master/sdk/sdk_journaling.md) -- this is essentially the same as a webhook just a pull instead of a push.

That said, it seems trivial to add the execution status to `current-execution:get` so I'll go ahead and do that. But really Journaling is a better fit for your use case.

**Comment by jwadolowski** [comment]
Thanks @justinedelson! That was really quick. And thanks for the hint, I'll definitely have a look at journaling API.
