### ISSUE TITLE
Prevent overwriting internal environment variables

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#285]
Some environment variables are used internally by AEMaaCS like `LOG_LEVEL`, `binaryStoreType`, `aemCloudAdministrators`, `imsOrganization`, `aemInstanceId`, ....

Setting those via aio should be prevented as this doesn't lead to the desired effect as built-in variables always take precedence over those set via Adobe IO.

This is especially crucial as there is currently no namespacing or a documentation of used variables available (https://github.com/AdobeDocs/experience-manager-cloud-service.en/issues/103) so one never knows if a set variable clashes with an internal one.

**Comment by justinedelson** [comment]
Makes sense. Marking this as blocked until a machine-readable list is published in docs.

**Comment by justinedelson** [comment]
@kwin It seems like in https://github.com/AdobeDocs/experience-manager-cloud-service.en/commit/7baacc953c88e1beb13be9878b635b6e5273dea2, the AEM documentation was updated to clarify that variables starting with `INTERNAL_` would be ignored. I've only been tracking the issue linked to in the description and just noticed the commit today.

What I'm thinking is that by default if any of the variables passed to `environment:set-variables` start with this prefix, a warning should be logged. But there should be a `--strict` flag that makes this a failure condition.

WDYT?

**Comment by kwin** [comment]
Having a `strict` flag emitting an error for variable clashes sounds good to me. Should be possible though to configure this by default (instead of giving it every time via CLI). Not sure though if really all internal variables have been renamed yet to stick to that naming guideline....

**Comment by justinedelson** [comment]
> Should be possible though to configure this by default (instead of giving it every time via CLI).

Makes sense.

> Not sure though if really all internal variables have been renamed yet to stick to that naming guideline....

Sure, but I don't see a reason to *not* implement validation based on what is documented. Might be worth commenting along these lines in the docs issue. I will try to keep an eye on that and see if new exceptions are added, but if you happen to notice any changes, please raise an issue here to update the validation pattern.

**Comment by kwin** [comment]
@justinedelson I added a comment to https://github.com/AdobeDocs/experience-manager-cloud-service.en/issues/103#issuecomment-857634059 because it seems Adobe is not adhering to that namespacing yet.
