### ISSUE TITLE
Console Warnings Cause CI/CD Tests to Fail

### ISSUE THREAD

**Issue by thoughtassassin** [adobe/aio-cli-plugin-cloudmanager#287]
**Expected Behavior**

The current state of the code should pass the CI/CD checks

**Actual Behavior**

The warnings that are thrown in set variables functions cause the CI/CD tests to fail.

**Reproduction Scenario, Platform, and Version**

I discovered this while submitting a pr for an unrelated issue

**Steps to Reproduce**

Submit a pull request

**Comment by justinedelson** [comment]
@thoughtassassin this is plainly not the case. See e.g. https://github.com/adobe/aio-cli-plugin-cloudmanager/runs/2399747084 (the most recent action on the main branch)

**Comment by thoughtassassin** [comment]
@justinedelson I didn't see that my PR failed because of a linting issue. The check that I saw failed gave a preview that showed those warnings so I thought that was the cause. When I checked this morning I saw that it was the linting that caused the checks to fail. I'll close this as it does not cause the checks to fail
