### ISSUE TITLE
Authentication Issue -  Unable to tail the AEM CS instance log using the AIO CLI

### ISSUE THREAD

**Issue by isandipan2016** [adobe/aio-cli-plugin-cloudmanager#294]
**Expected Behavior**

Expect to be able to tail the log of AEM as CS instance.

**Actual Behavior**

Getting the error message " Error: A passphrase is needed for your private-key. Use the --passphrase flag to specify one."

**Reproduction Scenario, Platform, and Version**

AIO CLI Version : 6.1.0 
Cloud Manager Plugin Version: v1.5.0

Also include the output of `aio -v` and `aio plugins`
karmakar@Sandipans-MBP ~ % aio -v
@adobe/aio-cli/6.0.0 darwin-x64 node-v12.18.2

karmakar@Sandipans-MBP ~ % aio plugins
@adobe/aio-cli-plugin-app 6.1.0
@adobe/aio-cli-plugin-cloudmanager 1.5.0

If this is related to authentication, include the output of `aio config:get ims.contexts.aio-cli-plugin-cloudmanager` but *do not* include the private key content *or* any access tokens.

karmakar@Sandipans-MBP ~ % aio config:get ims.contexts.aio-cli-plugin-cloudmanager
{
  client_id: "ff66e98a290f435a8ee6bb5a1c2f2056",
  client_secret: "Removed",
  technical_account_id: "8A1956725DEC589F0A495FA1@techacct.adobe.com",
  technical_account_email: "unused",
  ims_org_id: "Removed",
  private_key: "Removed",
  meta_scopes: [
    "ent_cloudmgr_sdk"
  ]
}

**Steps to Reproduce**

Note: This can't be reproduced by other team members but me.

Unable to tail the log of AEM CS sandbox instance. Getting the error "A passphrase is needed for your private-key. Use the --passphrase flag to specify one.". To mention, there is no passphrase for the private key that I am using.

To mention, other team member from MSFT can tail the log but me.

The following documentation was followed to tail the log.

https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/logs.html?lang=en#aio-cli-tail-logs

![image](https://user-images.githubusercontent.com/22338874/116472673-10921000-a82b-11eb-8d3f-352557b5573a.png)

**Comment by justinedelson** [comment]
Is this a private key you generated or one generated from the Adobe I/O console?

**Comment by jward-magento** [comment]
I had the same issue, but it was caused by the newlines being removed from the beginning and end of the private key.

**Comment by isandipan2016** [comment]
The private key was generated from the Adobe I/O console.

**Comment by jward-magento** [comment]
Can you attach the output of the config.json (remove the client secret)?

**Comment by jward-magento** [comment]
First, configure the credentials:

aio config:set ims.contexts.aio-cli-plugin-cloudmanager PATH_TO_CONFIG_JSON_FILE --file --json
Then, configure the private certificate:

aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key PATH_TO_PRIVATE_KEY_FILE --file
More information on setting up a Cloud Manager integration in the Adobe I/O console can be found here.

More information on IMS contexts can be found in the documentation of @adobe/aio-lib-ims.

Old Configuration Migration
Previous versions of this plugin used the configuration key jwt-auth. Upon execution, the plugin will automatically migrate these configurations. It will not delete the old configuration however and you may want to run

aio config:del jwt-auth
To clean up any dangling configuration unless it is necessary for other aio plugins.

This migration process is silent by default. You can enable debug logging by running any command where the environment variable LOG_LEVEL is set to debug, e.g.

LOG_LEVEL=debug aio cloudmanager:list-programs

**Comment by isandipan2016** [comment]
Here is the config.json file (appended the extension .txt to be able to upload it here).
[config.json.txt](https://github.com/adobe/aio-cli-plugin-cloudmanager/files/6395029/config.json.txt)

Tried the above steps and now getting a different error "Error: Cannot generate token because no plugin supports configuration". Attaching screenshot

![image](https://user-images.githubusercontent.com/22338874/116478062-5dc5b000-a832-11eb-826a-b82fcb9cc5fa.png)

**Comment by justinedelson** [comment]
It looks like there might still be some cases where `technical_account_email` is required -- some strange npm loading issues seems to cause this. I would suggest adding that field to the config.json file and rerunning those commands.

**Comment by justinedelson** [comment]
not fully related to the issue above, but I found an issue (#295) where the context definition check wasn't working correctly. Would suggest updating to version 1.6.1 of the plugin

**Comment by justinedelson** [comment]
Assuming this has been resolved
