### ISSUE TITLE
Tail logs for specific environment

### ISSUE THREAD

**Issue by mj2409** [adobe/aio-cli-plugin-cloudmanager#300]
**Expected Behavior**

To tail logs for a environment and configuration when you run following command:

aio cloudmanager:environment:tail-log 119266 "Publish Dispatcher" httpdaccess

**Actual Behavior**
Got error response on command line for the same. 

.local/share/@adobe/aio-cli/node_modules/@adobe/aio-lib-cloudmanager/src/index.js:193:20
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:45756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:45756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**Reproduction Scenario, Platform, and Version**

Any relevant information about the preconditions to reproduce the issue.
The list-environment command gives the list of all environments available which states that connection works perfectly.

**Comment by justinedelson** [comment]
Please follow the template. Specifically this is missing the plugin, aio and node versions

**Comment by justinedelson** [comment]
I believe this should be addressed in release 1.6.2 -- there was a missing error handling condition so you should now see the actual error message.
