### ISSUE TITLE
@adobe/aio-lib-ims will require node-12 or greater starting July 14th, 2021

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-cloudmanager#372]
Your module is dependent on `@adobe/aio-lib-ims`.

Adobe IMS is retiring` TLS 1.0` and` TLS 1.1` support on **July 14th, 202**1.
`TLSv1.2` is the default for node-12 or higher: https://nodejs.org/api/cli.html#cli_tls_min_v1_2

Therefore any calls to Adobe IMS using `@adobe/aio-lib-ims` using `node-10` will fail after the retirement date above. 

**This module should impose a minimum requirement of `node-12` going forward.** 

Add this to your `package.json`:
```
{
   "engineStrict": true, 
   "engines" : { 
         "node" : ">=12" 
    }
}
```

**Comment by justinedelson** [comment]
@shazron lazy question — is there a public doc reference for this change?

**Comment by justinedelson** [comment]
nevermind. found it: https://helpx.adobe.com/x-productkb/multi/eol-tls-support.html
