### ISSUE TITLE
Update "CREATING" status to "PENDING" in base-commerce-cli-command

### ISSUE THREAD

**Issue by thoughtassassin** [adobe/aio-cli-plugin-cloudmanager#409]
Currently, the status that base commerce cli command will poll the GET endpoint for a command is "RUNNING" and "CREATING." The API team changed the "CREATING" status to "PENDING." The file should be updated to reflect that change.

**Comment by justinedelson** [comment]
This was fixed in 2.4.0. Not sure why it didn't get flagged.
