### ISSUE TITLE
Add support for creating a pipeline

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aio-cli-plugin-cloudmanager#598]
Currently it is only possible to update a pipeline and delete a pipeline, but not creating a new pipeline.

Goal of this request:
- We would like to have a code quality run on every pull request branch, but it is currently not possible to have a regex for the code quality pipeline branch name (**would like to make a feature request for this too, if you could tell me how?**)
- Seeing as previous is not possible, we will make a new code quality pipeline per branch so that we can execute the code quality on the specific branch

**Comment by justinedelson** [comment]
The CLI cannot expose capabilities which are not available through the underlying API. This is really a feature request for the API which should be done through Adobe Support.

**Comment by royteeuwen** [comment]
@justinedelson  sure, how can this be done? what kind of support should i contact? I don't think I should / can open a daycare ticket for this?
