### ISSUE TITLE
Allow cli access content set and content flow APIs

### ISSUE THREAD

**Issue by zygw** [adobe/aio-cli-plugin-cloudmanager#670]
**Is your feature request related to a problem? Please describe.**
Allow access to content set and content flow APIs such as list content sets, start content flow, cancel content flow

**Describe the solution you'd like**
cli commands allowing viewing and changing contents set and content flows

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by kwin** [comment]
@zygw Any chance to get a release with this feature soono?

**Comment by zygw** [comment]
The code is merged.  There was an issue with the ubuntu version, followed by the codecov issues.
Not sure how to get the release kicked off again.


From: Konrad Windszus ***@***.***>
Date: Tuesday, May 23, 2023 at 04:41
To: adobe/aio-cli-plugin-cloudmanager ***@***.***>
Cc: Zygmunt Wiercioch ***@***.***>, Mention ***@***.***>
Subject: Re: [adobe/aio-cli-plugin-cloudmanager] Allow cli access content set and content flow APIs (Issue #670)

EXTERNAL: Use caution when clicking on links or opening attachments.



@zygw<https://github.com/zygw> Any chance to get a release with this feature soono?

**Comment by zygw** [comment]
What is the process of resolving this?
I merged the ubuntu update to get the job to run, without realizing that it would cause this failure.

Zyg


From: Konrad Windszus ***@***.***>
Date: Tuesday, May 23, 2023 at 07:36
To: adobe/aio-cli-plugin-cloudmanager ***@***.***>
Cc: Zygmunt Wiercioch ***@***.***>, Mention ***@***.***>
Subject: Re: [adobe/aio-cli-plugin-cloudmanager] Allow cli access content set and content flow APIs (Issue #670)

EXTERNAL: Use caution when clicking on links or opening attachments.



The release failed as you can see in https://github.com/adobe/aio-cli-plugin-cloudmanager/actions/runs/4983477450/jobs/8921166037.

**Comment by justinedelson** [comment]
FWIW @zygw https://github.com/orgs/community/discussions/25305 and https://stackoverflow.com/a/76135647 provide potential solutions for this. Or just turn branch protection off.

**Comment by kwin** [comment]
@zygw Any idea how to continue here? Who at Adobe took over ownership of this plugin after @justinedelson left?

**Comment by kwin** [comment]
Thanks @zygw an you set the milestone for this issue and close it then?

**Comment by zygw** [comment]
Released as 4.1.0
