### ISSUE TITLE
Support OAuth Server-to-Server credential

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-cloudmanager#671]
As JWT service authentication is deprecated the new OAuth authentication should be supported in parallel. It is described in https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/implementation/.

**Comment by kwin** [comment]
This requires https://github.com/adobe/aio-lib-ims/issues/120.

**Comment by sanith01988** [comment]
> This requires [adobe/aio-lib-ims#120](https://github.com/adobe/aio-lib-ims/issues/120).

v6.4.0 already released…But this is not added to aio-plugin-cloudmanager. Still package.json referring to v6.4.0 for aio-lib-ims. Any idea when this feature will be available in aio-cloud-manager? Hope once package.json for aio-lib-ims updated and sufficient change is made, the aio-cloud-manager will support authentication with OauthS2S without browser authentication.

**Comment by royteeuwen** [comment]
+1, any idea when this will be added / documented on how to authenticate with oauth?

**Comment by Rudrakle** [comment]
Hi guys, any updates on this feature? Is this available and documented somewhere? Thank you :)

**Comment by imaadghouri85** [comment]
Hello,
Any update when this feature become available as JWT service token mechanism will get deprecated in the near future ?

**Comment by kwin** [comment]
According to https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration/ JWT authentication will no longer be available for new apps from 1st of May 2024, so this becomes crucial.

**Comment by forbesd7** [comment]
FYI there is a working 'solution' in this thread https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/676

**Comment by kritikash18** [comment]
official support added in latest release
