### ISSUE TITLE
update AEM build for dev env: update-pipeline

### ISSUE THREAD

**Issue by knennigtri** [adobe/aio-cli-plugin-cloudmanager#83]
### Expected Behaviour

`$ aio cloudmanager:update-pipeline --programId=1234 123456 --updateAemBuild`

Since Dev environments don't autoupdate, is it possible to get an option for update-pipeline to update to the latest AEM build? It seems that update-pipeline command can only update the git branch attached to the pipeline. This is a nice feature in the UI that would be helpful in this tool.

**Comment by justinedelson** [comment]
This functionality is not exposed through the public API, so can't be added to the CLI.

**Comment by kwin** [comment]
FTR: https://github.com/AdobeDocs/cloudmanager-api-docs/issues/29
